apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: container-01
        image: python:alpine3.8
        command: ["sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 3000

