apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    app: demo
spec:
  containers:
  - name: container-01
    image: python:alpine3.8
    ports:
    - containerPort: 3000
    command: ["sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: test-volume
      mountPath: /tmp
  - name: container-02
    image: python:alpine3.8
    ports:
    - containerPort: 3001
    command: ["sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: test-volume
      mountPath: /tmp
  volumes:
  - name: test-volume
    hostPath:
      path: "/tmp"

