apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    app: demo
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            #- amd64
            - x86_64
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1 
        preference:
          matchExpressions:
          - key: xyz
            operator: In 
            values:
            - abc
  containers:
  - name: container-01
    image: python:alpine3.8
    ports:
    - containerPort: 3000
    command: ["sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    - name: test-volume
      mountPath: /tmp
  volumes:
  - name: test-volume
    hostPath:
      path: "/tmp"

