apiVersion: v1
kind: Pod
metadata:
  name: kube-demo
  labels:
    app: python
spec:
  containers:
  - name: python1
    image: python:alpine3.8
    ports:
    - containerPort: 3000
    command: ["sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
