apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: ns1
subjects:
- kind: User
  name: usr1
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: usr2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
