apiVersion: v1
kind: Service
metadata:
  name: svc-demo
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3000
    nodePort: 30001 
    protocol: TCP	# optional
    name: mysvc
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: container-01
        image: python:alpine3.8
        command: ["sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 3000

