apiVersion: v1
kind: Pod
metadata:
  name: sa1-token-demo
  labels:
    app: python
spec:
  serviceAccountName: sa1
  containers:
  - name: python1
    image: python:alpine3.8
    volumeMounts:
    - mountPath: /var/run/secrets/
      name: sa1-token
    ports:
    - containerPort: 3000
    command: ["sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  volumes:
  - name: sa1-token
    projected:
      sources:
      - serviceAccountToken:
          path: abc
          expirationSeconds: 600
          audience: api
